### ISSUE TITLE
DESeq2 Shows same results for different data

### ISSUE THREAD

**Issue by pradyumnasagar** [likelet/IDEA#2]
Hi there,
I have a data with 4 conditions and have the matrix of experimental design, when I run DESeq2 to compare condition1 to  condition4 and condition 2 to condtion4 both shows the same result, while edgeR gives different results for same analysis, I think DESeq2 script has some problem, can you please rectify it?
Thanks
Pradyumna

**Comment by likelet** [comment]
Hi Pradyumna
Thanks for your  bug post, i will check the script and fix it ASAP

**Comment by likelet** [comment]
Hi Pradyumna
I checked the code, there is indeed a missing parameter for DESeq analysis. I have fixed it already and the result reactively update while comparing situation changed.
Please replace the  'inst' folder with the latest code.
Thanks very much for testing IDEA.  
Can I close this issue now?

**Comment by likelet** [comment]
closed  due to time

**Comment by pradyumnasagar** [comment]
Thanks it worked
