### ISSUE TITLE
Output file name Suggestion

### ISSUE THREAD

**Issue by pradyumnasagar** [likelet/IDEA#5]
hello,
I would like to suggest that it would be helpful if the output file names are saved in the name of condition instead of time and date. like currently output name for deseq analysis is like `DEseqDEresult2017-03-07 22-09-12.csv` instead if it is like `DEseqDEresultCondition1vsCondition2.csv` it will be easy to differentiate the files.

**Comment by likelet** [comment]
Thanks for your suggestion. Code has already been updated as you suggested .
File names were changed by adding condition information.
Qi

**Comment by pradyumnasagar** [comment]
Thank you
