### ISSUE TITLE
Cant run IDEA

### ISSUE THREAD

**Issue by pradyumnasagar** [likelet/IDEA#6]
hi,
When I try to run idea, it starts but when I upload a file or use example data, it stuck in loading in progress screen and don't proceed further, the following is the message displayed in the terminal.

> library(IDEA)
> runIDEA()
Loading required package: shiny

Listening on http://127.0.0.1:3759
Loading required package: RJSONIO
Loading required package: plyr

Attaching package: ‘shinysky’

The following object is masked from ‘package:shiny’:

    actionButton

Loading required package: S4Vectors
Loading required package: stats4
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, cbind, colnames, do.call,
    duplicated, eval, evalq, Filter, Find, get, grep, grepl, intersect,
    is.unsorted, lapply, lengths, Map, mapply, match, mget, order,
    paste, pmax, pmax.int, pmin, pmin.int, Position, rank, rbind,
    Reduce, rownames, sapply, setdiff, sort, table, tapply, union,
    unique, unsplit, which, which.max, which.min

Attaching package: ‘S4Vectors’

The following object is masked from ‘package:plyr’:

    rename

The following objects are masked from ‘package:base’:

    colMeans, colSums, expand.grid, rowMeans, rowSums

Loading required package: IRanges

Attaching package: ‘IRanges’

The following object is masked from ‘package:plyr’:

    desc

Loading required package: GenomicRanges
Loading required package: GenomeInfoDb
Loading required package: SummarizedExperiment
Loading required package: Biobase
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Warning in is.na(x[[i]]) :
  is.na() applied to non-(list or vector) of type 'environment'
'BiocParallel' did not register default BiocParallelParams:
  invalid class “MulticoreParam” object: 1: ‘cluster’, ‘.clusterargs’, ‘.uid’, ‘RNGseed’ must be length 1
invalid class “MulticoreParam” object: 2: ‘.clusterargs’, ‘.controlled’, ‘logdir’, ‘resultdir’ must be length 1
Loading required package: limma

Attaching package: ‘limma’

The following object is masked from ‘package:DESeq2’:

    plotMA

The following object is masked from ‘package:BiocGenerics’:

    plotMA

Attaching package: ‘gplots’

The following object is masked from ‘package:IRanges’:

    space

The following object is masked from ‘package:S4Vectors’:

    space

The following object is masked from ‘package:stats’:

    lowess

Loading required package: combinat

Attaching package: ‘combinat’

The following object is masked from ‘package:utils’:

    combn

Loading required package: splines
Loading required package: impute
Loading required package: matrixStats

Attaching package: ‘matrixStats’

The following object is masked from ‘package:SummarizedExperiment’:

    rowRanges

The following objects are masked from ‘package:Biobase’:

    anyMissing, rowMedians

The following object is masked from ‘package:plyr’:

    count

Loading required package: Matrix

Attaching package: ‘Matrix’

The following object is masked from ‘package:S4Vectors’:

    expand

Attaching package: ‘NOISeq’

The following object is masked from ‘package:edgeR’:

    rpkm

Loading required package: grid
Loading required package: futile.logger

Attaching package: ‘RobustRankAggreg’

The following object is masked from ‘package:Matrix’:

    rankMatrix

converting counts to integer mode
estimating size factors
estimating dispersions
gene-wise dispersion estimates
mean-dispersion relationship
final dispersion estimates
fitting model and testing
[1] "condition"
Warning: Error in checkContrast: 'contrast', as a character vector of length 3, should have the form:
contrast = c('factorName','numeratorLevel','denominatorLevel'),
see the manual page of ?results for more information
Stack trace (innermost first):
    97: checkContrast
    96: results
    95: DEseqGetNBDEdata [/usr/local/lib/R/site-library/IDEA/IDEA/server.R#1061]
    94: <reactive:getDEseqResultTable> [/usr/local/lib/R/site-library/IDEA/IDEA/server.R#1024]
    83: getDEseqResultTable
    82: renderDataTable [/usr/local/lib/R/site-library/IDEA/IDEA/server.R#1032]
    81: func
    80: origRenderFunc
    79: output$DEseqTable
     2: shiny::runApp
     1: runIDEA

 *** caught segfault ***
address 0xb7, cause 'memory not mapped'

Traceback:
 1: .External("cairo_create_new_device", as.character(ctype), file,     width, height, pointsize, bg, canvas, umpl, dpi, ..., PACKAGE = "Cairo")
 2: Cairo(width, height, type = "png", file = filename, pointsize = pointsize,     bg = bg, res = res, ...)
 3: pngfun(filename = filename, width = width, height = height, res = res,     ...)
 4: (function (func, filename = tempfile(fileext = ".png"), width = 400,     height = 400, res = 72, ...) {    if (capabilities("aqua")) {        pngfun <- grDevices::png    }    else if ((getOption("shiny.usecairo") %OR% TRUE) && nchar(system.file(package = "Cairo"))) {        pngfun <- Cairo::CairoPNG    }    else {        pngfun <- grDevices::png    }    pngfun(filename = filename, width = width, height = height,         res = res, ...)    op <- graphics::par(mar = rep(0, 4))    tryCatch(graphics::plot.new(), finally = graphics::par(op))    dv <- grDevices::dev.cur()    on.exit(grDevices::dev.off(dv), add = TRUE)    func()    filename})(function () {    success <- FALSE    tryCatch({        grDevices::dev.control(displaylist = "enable")        result <- withVisible(func())        success <- TRUE    }, finally = {        if (!success) {            getDims()        }    })    if (result$visible) {        utils::capture.output({            plotResult <<- ..stacktraceon..(print(result$value))        })    }    recordedPlot <<- grDevices::recordPlot()    if (inherits(plotResult, "ggplot_build_gtable")) {        coordmap <<- getGgplotCoordmap(plotResult, pixelratio,             res)    }    else {        coordmap <<- getPrevPlotCoordmap(dims$width, dims$height)    }}, width = 629.999983310699, height = 629.999983310699, res = 64.7999982833862)
 5: do.call(plotPNG, c(plotFunc, width = dims$width * pixelratio,     height = dims$height * pixelratio, res = res * pixelratio,     args))
 6: ..stacktraceoff..(do.call(plotPNG, c(plotFunc, width = dims$width *     pixelratio, height = dims$height * pixelratio, res = res *     pixelratio, args)))
 7: `<reactive:plotObj>`(...)
 8: ..stacktraceon..(`<reactive:plotObj>`(...))
 9: .func()
10: withVisible(.func())
11: withCallingHandlers({    .error <<- FALSE    withVisible(.func())}, error = function(cond) {    .value <<- cond    .error <<- TRUE    .visible <<- FALSE})
12: contextFunc()
13: env$runWith(self, func)
14: withReactiveDomain(.domain, {    env <- .getReactiveEnvironment()    .graphEnterContext(id)    on.exit(.graphExitContext(id), add = TRUE)    env$runWith(self, func)})
15: ctx$run(function() {    result <- withCallingHandlers({        .error <<- FALSE        withVisible(.func())    }, error = function(cond) {        .value <<- cond        .error <<- TRUE        .visible <<- FALSE    })    .value <<- result$value    .visible <<- result$visible})
16: self$.updateValue()
17: ..stacktraceoff..(self$.updateValue())
18: plotObj()
19: origRenderFunc(...)
20: `output$DEseqDispersionsPlot`(...)
21: ..stacktraceon..(`output$DEseqDispersionsPlot`(...))
22: orig(name = name, shinysession = self)
23: func()
24: withCallingHandlers(expr, error = function(e) {    if (is.null(attr(e, "stack.trace", exact = TRUE))) {        calls <- sys.calls()        attr(e, "stack.trace") <- calls        stop(e)    }})
25: captureStackTraces(expr)
26: withCallingHandlers(captureStackTraces(expr), error = function(e) {    if (inherits(e, "shiny.silent.error"))         return()    handle <- getOption("shiny.error")    if (is.function(handle))         handle()})
27: shinyCallingHandlers(func())
28: doTryCatch(return(expr), name, parentenv, handler)
29: tryCatchOne(expr, names, parentenv, handlers[[1L]])
30: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
31: doTryCatch(return(expr), name, parentenv, handler)
32: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),     names[nh], parentenv, handlers[[nh]])
33: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
34: doTryCatch(return(expr), name, parentenv, handler)
35: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),     names[nh], parentenv, handlers[[nh]])
36: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
37: doTryCatch(return(expr), name, parentenv, handler)
38: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),     names[nh], parentenv, handlers[[nh]])
39: tryCatchList(expr, classes, parentenv, handlers)
40: tryCatch(shinyCallingHandlers(func()), shiny.custom.error = function(cond) {    if (isTRUE(getOption("show.error.messages")))         printError(cond)    structure(list(), class = "try-error", condition = cond)}, shiny.output.cancel = function(cond) {    structure(list(), class = "cancel-output")}, shiny.silent.error = function(cond) {    structure(list(), class = "try-error", condition = cond)}, error = function(cond) {    if (isTRUE(getOption("show.error.messages")))         printError(cond)    if (getOption("shiny.sanitize.errors", FALSE)) {        cond <- simpleError(paste("An error has occurred. Check your",             "logs or contact the app author for", "clarification."))    }    invisible(structure(list(), class = "try-error", condition = cond))}, finally = {    private$sendMessage(recalculating = list(name = name, status = "recalculated"))})
41: observerFunc()
42: doTryCatch(return(expr), name, parentenv, handler)
43: tryCatchOne(expr, names, parentenv, handlers[[1L]])
44: tryCatchList(expr, classes, parentenv, handlers)
45: tryCatch(if (..stacktraceon) ..stacktraceon..(observerFunc()) else observerFunc(),     shiny.silent.error = function(e) NULL)
46: contextFunc()
47: env$runWith(self, func)
48: withReactiveDomain(.domain, {    env <- .getReactiveEnvironment()    .graphEnterContext(id)    on.exit(.graphExitContext(id), add = TRUE)    env$runWith(self, func)})
49: ctx$run(.func)
50: run()
51: withCallingHandlers(expr, error = function(e) {    if (is.null(attr(e, "stack.trace", exact = TRUE))) {        calls <- sys.calls()        attr(e, "stack.trace") <- calls        stop(e)    }})
52: captureStackTraces(expr)
53: withCallingHandlers(captureStackTraces(expr), error = function(e) {    if (inherits(e, "shiny.silent.error"))         return()    handle <- getOption("shiny.error")    if (is.function(handle))         handle()})
54: shinyCallingHandlers(run())
55: doTryCatch(return(expr), name, parentenv, handler)
56: tryCatchOne(expr, names, parentenv, handlers[[1L]])
57: tryCatchList(expr, classes, parentenv, handlers)
58: tryCatch({    if (!.destroyed)         shinyCallingHandlers(run())}, error = function(e) {    printError(e)    if (!is.null(.domain)) {        .domain$unhandledError(e)    }})
59: flushCallback()
60: FUN(X[[i]], ...)
61: lapply(.flushCallbacks, function(flushCallback) {    flushCallback()})
62: ctx$executeFlushCallbacks()
63: .getReactiveEnvironment()$flush()
64: flushReact()
65: force(expr)
66: withRestoreContext(shinysession$restoreContext, {    msg$data <- applyInputHandlers(msg$data)    switch(msg$method, init = {        serverFunc <- withReactiveDomain(NULL, serverFuncSource())        if (!identicalFunctionBodies(serverFunc, appvars$server)) {            appvars$server <- serverFunc            if (!is.null(appvars$server)) {                attr(appvars$server, "shinyServerFunction") <- TRUE                registerDebugHook("server", appvars, "Server Function")            }        }        if (.globals$showcaseOverride && exists(".clientdata_url_search",             where = msg$data)) {            mode <- showcaseModeOfQuerystring(msg$data$.clientdata_url_search)            if (!is.null(mode)) shinysession$setShowcase(mode)        }        shinysession$manageInputs(msg$data)        if (!is.null(msg$data$.clientdata_singletons)) {            shinysession$singletons <- strsplit(msg$data$.clientdata_singletons,                 ",")[[1]]        }        local({            args <- argsForServerFunc(serverFunc, shinysession)            withReactiveDomain(shinysession, {                do.call(wrapFunctionLabel(appvars$server, "server",                   ..stacktraceon = TRUE), args)            })        })    }, update = {        shinysession$manageInputs(msg$data)    }, shinysession$dispatch(msg))    shinysession$manageHiddenOutputs()    if (exists(".shiny__stdout", globalenv()) && exists("HTTP_GUID",         ws$request)) {        shiny_stdout <- get(".shiny__stdout", globalenv())        writeLines(paste("_n_flushReact ", get("HTTP_GUID", ws$request),             " @ ", sprintf("%.3f", as.numeric(Sys.time())), sep = ""),             con = shiny_stdout)        flush(shiny_stdout)        flushReact()        writeLines(paste("_x_flushReact ", get("HTTP_GUID", ws$request),             " @ ", sprintf("%.3f", as.numeric(Sys.time())), sep = ""),             con = shiny_stdout)        flush(shiny_stdout)    }    else {        flushReact()    }    flushAllSessions()})
67: withReactiveDomain(shinysession, {    if (is.character(msg))         msg <- charToRaw(msg)    traceOption <- getOption("shiny.trace", FALSE)    if (isTRUE(traceOption) || traceOption == "recv") {        if (binary)             message("RECV ", "$$binary data$$")        else message("RECV ", rawToChar(msg))    }    if (identical(charToRaw("\003\xe9"), msg))         return()    msg <- decodeMessage(msg)    if (is.null(shinysession$restoreContext)) {        bookmarkStore <- getShinyOption("bookmarkStore", default = "disable")        if (bookmarkStore == "disable") {            shinysession$restoreContext <- RestoreContext$new()        }        else {            shinysession$restoreContext <- RestoreContext$new(msg$data$.clientdata_url_search)        }    }    withRestoreContext(shinysession$restoreContext, {        msg$data <- applyInputHandlers(msg$data)        switch(msg$method, init = {            serverFunc <- withReactiveDomain(NULL, serverFuncSource())            if (!identicalFunctionBodies(serverFunc, appvars$server)) {                appvars$server <- serverFunc                if (!is.null(appvars$server)) {                  attr(appvars$server, "shinyServerFunction") <- TRUE                  registerDebugHook("server", appvars, "Server Function")                }            }            if (.globals$showcaseOverride && exists(".clientdata_url_search",                 where = msg$data)) {                mode <- showcaseModeOfQuerystring(msg$data$.clientdata_url_search)                if (!is.null(mode)) shinysession$setShowcase(mode)            }            shinysession$manageInputs(msg$data)            if (!is.null(msg$data$.clientdata_singletons)) {                shinysession$singletons <- strsplit(msg$data$.clientdata_singletons,                   ",")[[1]]            }            local({                args <- argsForServerFunc(serverFunc, shinysession)                withReactiveDomain(shinysession, {                  do.call(wrapFunctionLabel(appvars$server, "server",                     ..stacktraceon = TRUE), args)                })            })        }, update = {            shinysession$manageInputs(msg$data)        }, shinysession$dispatch(msg))        shinysession$manageHiddenOutputs()        if (exists(".shiny__stdout", globalenv()) && exists("HTTP_GUID",             ws$request)) {            shiny_stdout <- get(".shiny__stdout", globalenv())            writeLines(paste("_n_flushReact ", get("HTTP_GUID",                 ws$request), " @ ", sprintf("%.3f", as.numeric(Sys.time())),                 sep = ""), con = shiny_stdout)            flush(shiny_stdout)            flushReact()            writeLines(paste("_x_flushReact ", get("HTTP_GUID",                 ws$request), " @ ", sprintf("%.3f", as.numeric(Sys.time())),                 sep = ""), con = shiny_stdout)            flush(shiny_stdout)        }        else {            flushReact()        }        flushAllSessions()    })})
68: messageHandler(binary, msg)
69: withCallingHandlers(expr, error = function(e) {    if (is.null(attr(e, "stack.trace", exact = TRUE))) {        calls <- sys.calls()        attr(e, "stack.trace") <- calls        stop(e)    }})
70: captureStackTraces(expr)
71: withCallingHandlers(captureStackTraces(expr), error = function(cond) {    if (inherits(cond, "shiny.silent.error"))         return()    if (isTRUE(getOption("show.error.messages"))) {        printError(cond, full = full, offset = offset)    }})
72: withLogErrors(messageHandler(binary, msg))
73: handler(binary, message)
74: doTryCatch(return(expr), name, parentenv, handler)
75: tryCatchOne(expr, names, parentenv, handlers[[1L]])
76: tryCatchList(expr, classes, parentenv, handlers)
77: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = outFile)        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
78: try(handler(binary, message))
79: (function (handle, binary, message) {    for (handler in .wsconns[[as.character(handle)]]$.messageCallbacks) {        result <- try(handler(binary, message))        if (inherits(result, "try-error")) {            .wsconns[[as.character(handle)]]$close()            return()        }    }})("44250960", FALSE, "{\"method\":\"update\",\"data\":{\".clientdata_output_DEseqDispersionsPlot_width\":800,\".clientdata_output_DEseqDispersionsPlot_height\":0,\".clientdata_output_DEseqMAplot_width\":1097,\".clientdata_output_DEseqMAplot_height\":0,\".clientdata_output_DESeqVolcanoPlotRender_width\":1097,\".clientdata_output_DESeqVolcanoPlotRender_height\":0,\".clientdata_output_DESeqheatmapRender_width\":1097,\".clientdata_output_DESeqheatmapRender_height\":0,\".clientdata_output_DESeqPvalueDistributionplotRender_width\":1097,\".clientdata_output_DESeqPvalueDistributionplotRender_height\":0,\".clientdata_output_DataInputswitchUI_hidden\":true,\".clientdata_output_designSwitchUI_hidden\":true,\".clientdata_output_interestvariablesUI_hidden\":true,\".clientdata_output_ConditionSelectionUI_hidden\":true,\".clientdata_output_DEseqTable_hidden\":false,\".clientdata_output_DESeqDisperplotDownload_hidden\":false,\".clientdata_output_DEseqDispersionsPlot_hidden\":false,\".clientdata_output_DEseqMAplotDownload_hidden\":false,\".clientdata_output_DEseqMAplot_hidden\":false,\".clientdata_output_normalizeFactor_hidden\":false,\".clientdata_output_DEseqVolcanoPlotDownload_hidden\":false,\".clientdata_output_DESeqVolcanoPlotRender_hidden\":false,\".clientdata_output_DESeqHeatmapDownload_hidden\":false,\".clientdata_output_DESeqheatmapRender_hidden\":false,\".clientdata_output_DESeqPvalueDistributionplotDownload_hidden\":false,\".clientdata_output_DESeqPvalueDistributionplotRender_hidden\":false,\".clientdata_output_comparisonSampleTextRenderUI2_hidden\":false,\".clientdata_output_DEseqdownloadDEtable_hidden\":false,\".clientdata_output_DownloadDESeqReport_hidden\":false}}")
80: eval(substitute(expr), envir, enclos)
81: eval(substitute(expr), envir, enclos)
82: eval(substitute(expr), envir, enclos)
83: evalq((function (handle, binary, message) {    for (handler in .wsconns[[as.character(handle)]]$.messageCallbacks) {        result <- try(handler(binary, message))        if (inherits(result, "try-error")) {            .wsconns[[as.character(handle)]]$close()            return()        }    }})("44250960", FALSE, "{\"method\":\"update\",\"data\":{\".clientdata_output_DEseqDispersionsPlot_width\":800,\".clientdata_output_DEseqDispersionsPlot_height\":0,\".clientdata_output_DEseqMAplot_width\":1097,\".clientdata_output_DEseqMAplot_height\":0,\".clientdata_output_DESeqVolcanoPlotRender_width\":1097,\".clientdata_output_DESeqVolcanoPlotRender_height\":0,\".clientdata_output_DESeqheatmapRender_width\":1097,\".clientdata_output_DESeqheatmapRender_height\":0,\".clientdata_output_DESeqPvalueDistributionplotRender_width\":1097,\".clientdata_output_DESeqPvalueDistributionplotRender_height\":0,\".clientdata_output_DataInputswitchUI_hidden\":true,\".clientdata_output_designSwitchUI_hidden\":true,\".clientdata_output_interestvariablesUI_hidden\":true,\".clientdata_output_ConditionSelectionUI_hidden\":true,\".clientdata_output_DEseqTable_hidden\":false,\".clientdata_output_DESeqDisperplotDownload_hidden\":false,\".clientdata_output_DEseqDispersionsPlot_hidden\":false,\".clientdata_output_DEseqMAplotDownload_hidden\":false,\".clientdata_output_DEseqMAplot_hidden\":false,\".clientdata_output_normalizeFactor_hidden\":false,\".clientdata_output_DEseqVolcanoPlotDownload_hidden\":false,\".clientdata_output_DESeqVolcanoPlotRender_hidden\":false,\".clientdata_output_DESeqHeatmapDownload_hidden\":false,\".clientdata_output_DESeqheatmapRender_hidden\":false,\".clientdata_output_DESeqPvalueDistributionplotDownload_hidden\":false,\".clientdata_output_DESeqPvalueDistributionplotRender_hidden\":false,\".clientdata_output_comparisonSampleTextRenderUI2_hidden\":false,\".clientdata_output_DEseqdownloadDEtable_hidden\":false,\".clientdata_output_DownloadDESeqReport_hidden\":false}}"),     <environment>)
84: doTryCatch(return(expr), name, parentenv, handler)
85: tryCatchOne(expr, names, parentenv, handlers[[1L]])
86: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
87: doTryCatch(return(expr), name, parentenv, handler)
88: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),     names[nh], parentenv, handlers[[nh]])
89: tryCatchList(expr, classes, parentenv, handlers)
90: tryCatch(evalq((function (handle, binary, message) {    for (handler in .wsconns[[as.character(handle)]]$.messageCallbacks) {        result <- try(handler(binary, message))        if (inherits(result, "try-error")) {            .wsconns[[as.character(handle)]]$close()            return()        }    }})("44250960", FALSE, "{\"method\":\"update\",\"data\":{\".clientdata_output_DEseqDispersionsPlot_width\":800,\".clientdata_output_DEseqDispersionsPlot_height\":0,\".clientdata_output_DEseqMAplot_width\":1097,\".clientdata_output_DEseqMAplot_height\":0,\".clientdata_output_DESeqVolcanoPlotRender_width\":1097,\".clientdata_output_DESeqVolcanoPlotRender_height\":0,\".clientdata_output_DESeqheatmapRender_width\":1097,\".clientdata_output_DESeqheatmapRender_height\":0,\".clientdata_output_DESeqPvalueDistributionplotRender_width\":1097,\".clientdata_output_DESeqPvalueDistributionplotRender_height\":0,\".clientdata_output_DataInputswitchUI_hidden\":true,\".clientdata_output_designSwitchUI_hidden\":true,\".clientdata_output_interestvariablesUI_hidden\":true,\".clientdata_output_ConditionSelectionUI_hidden\":true,\".clientdata_output_DEseqTable_hidden\":false,\".clientdata_output_DESeqDisperplotDownload_hidden\":false,\".clientdata_output_DEseqDispersionsPlot_hidden\":false,\".clientdata_output_DEseqMAplotDownload_hidden\":false,\".clientdata_output_DEseqMAplot_hidden\":false,\".clientdata_output_normalizeFactor_hidden\":false,\".clientdata_output_DEseqVolcanoPlotDownload_hidden\":false,\".clientdata_output_DESeqVolcanoPlotRender_hidden\":false,\".clientdata_output_DESeqHeatmapDownload_hidden\":false,\".clientdata_output_DESeqheatmapRender_hidden\":false,\".clientdata_output_DESeqPvalueDistributionplotDownload_hidden\":false,\".clientdata_output_DESeqPvalueDistributionplotRender_hidden\":false,\".clientdata_output_comparisonSampleTextRenderUI2_hidden\":false,\".clientdata_output_DEseqdownloadDEtable_hidden\":false,\".clientdata_output_DownloadDESeqReport_hidden\":false}}"),     <environment>), error = function (x) x, interrupt = function (x) x)
91: .Call("httpuv_run", PACKAGE = "httpuv", timeoutMillis)
92: run(timeoutMs)
93: service(timeout)
94: serviceApp()
95: withCallingHandlers(expr, error = function(e) {    if (is.null(attr(e, "stack.trace", exact = TRUE))) {        calls <- sys.calls()        attr(e, "stack.trace") <- calls        stop(e)    }})
96: captureStackTraces({    scheduleFlush()    while (!.globals$stopped) {        serviceApp()        Sys.sleep(0.001)    }})
97: ..stacktraceoff..(captureStackTraces({    scheduleFlush()    while (!.globals$stopped) {        serviceApp()        Sys.sleep(0.001)    }}))
98: shiny::runApp(system.file("IDEA", package = "IDEA"))
99: runIDEA()

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection:

**Comment by likelet** [comment]
it seems stuck at package loading step and IDEA can only run smoothly after all required packages loaded (obviously  I have no idea to fix it at present). can you paste your R sessionInfo here to make me know details on your R environment. By typing the following command on your R env
`library(IDEA)`
`sessionInfo()`

**Comment by pradyumnasagar** [comment]
> library(IDEA)
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_IN       LC_NUMERIC=C         LC_TIME=en_IN       
 [4] LC_COLLATE=en_IN     LC_MONETARY=en_IN    LC_MESSAGES=en_IN   
 [7] LC_PAPER=en_IN       LC_NAME=C            LC_ADDRESS=C        
[10] LC_TELEPHONE=C       LC_MEASUREMENT=en_IN LC_IDENTIFICATION=C 

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] IDEA_0.99.0

loaded via a namespace (and not attached):
[1] compiler_3.4.0

**Comment by likelet** [comment]
Sorry for late reply, i actually also got the same issue from my local friend.  Recently  i have been working with this and also do some updation of IDEA.  The new version would be released soon  and thanks in advance for following IDEA so far.

best wishes.

**Comment by likelet** [comment]
hi pradyumnasagar
I think I figured out what happened in your machine, It seems  caused by a memory issue. So what dose your data like (how many columns and rows?) and so as your computer information?

**Comment by pradyumnasagar** [comment]
hi 
sorry, I could not repeat the issue, I formated the machine and re installed the IDEA, works fine now.
